import 'stock_pile.dart';
import '../../ship/systems/ship_system.dart';
import '../../ship/systems/weapons.dart';

final Map<StockSystem, WeaponData> stockWeapons = {
  StockSystem.wepFedLaser1: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Fed Laser Mk 1",
        mass: 10, baseCost: 100, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 1,
    dmgDiceSides: 60,
    dmgBase: 1,
    dmgType: DamageType.photonic,
    energyRate: 20,
    fireRate: 10,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .5),
    accuracyRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .33),
  ),

  StockSystem.wepFedLaser2: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Fed Laser Mk 2",
        mass: 10, baseCost: 250, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 4,
    dmgDiceSides: 20,
    dmgBase: 8,
    dmgType: DamageType.photonic,
    energyRate: 20,
    fireRate: 8,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .33),
    accuracyRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .25),
  ),

  StockSystem.wepFedLaser3: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Fed Laser Mk 3",
        mass: 10, baseCost: 500, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 5,
    dmgDiceSides: 25,
    dmgBase: 12,
    dmgType: DamageType.photonic,
    energyRate: 20,
    fireRate: 8,
    baseAccuracy: .9,
    dmgRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .33),
    accuracyRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .2),
  ),

  StockSystem.wepPlasmaRay: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Plasma Ray",
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 4,
    dmgDiceSides: 60,
    dmgBase: 16,
    dmgType: DamageType.plasma,
    energyRate: 36,
    fireRate: 16,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .2),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .1),
  ),

  StockSystem.wepGravRifle: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Gravimetric Pulse Rifle",
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .6),
    dmgDice: 4,
    dmgDiceSides: 24,
    dmgBase: 16,
    dmgType: DamageType.gravitron,
    energyRate: 12,
    fireRate: 4,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .2),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .1),
  ),

  StockSystem.wepVibraSlap: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Cosmosonic Emitter",
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .6),
    dmgDice: 8,
    dmgDiceSides: 24,
    dmgBase: 32,
    dmgType: DamageType.sonic,
    energyRate: 48,
    fireRate: 24,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 2, maxRange: 12, closeFalloff: .01, farFalloff: .05),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 2, maxRange: 12, closeFalloff: .01, farFalloff: .05),
  ),

  StockSystem.wepNeuRad: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Neutronic Radiator",
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .6),
    dmgDice: 8,
    dmgDiceSides: 32,
    dmgBase: 24,
    dmgType: DamageType.neutrino,
    energyRate: 60,
    fireRate: 32,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .1),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .1),
  ),

  StockSystem.wepThermalLance: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Thermal Lance",
        mass: 10, baseCost: 2000, baseRepairCost: 1.5, powerDraw: .9),
    dmgDice: 4,
    dmgDiceSides: 160,
    dmgBase: 50,
    dmgType: DamageType.fire,
    energyRate: 80,
    fireRate: 16,
    baseAccuracy: .5,
    dmgRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .25),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .5),
  ),

  StockSystem.wepQuarkSplitter: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Quark Splitter",
        mass: 10, baseCost: 80000, baseRepairCost: 5, powerDraw: 1.2),
    dmgDice: 3,
    dmgDiceSides: 512,
    dmgBase: 50,
    dmgType: DamageType.neutrino,
    energyRate: 480,
    fireRate: 12,
    baseAccuracy: .16,
    dmgRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .25),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .5),
  ),

  StockSystem.wepGammapult: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Gammapult",
        mass: 10, baseCost: 2000, baseRepairCost: 5, powerDraw: 1.7),
    dmgDice: 4,
    dmgDiceSides: 255,
    dmgBase: 92,
    dmgType: DamageType.ion,
    energyRate: 108,
    fireRate: 16,
    baseAccuracy: .5,
    dmgRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .25),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .5),
  ),

  StockSystem.wepCosmogripher: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Cosmogripher",
        mass: 10, baseCost: 2000, baseRepairCost: 5, powerDraw: 2.25),
    dmgDice: 5,
    dmgDiceSides: 255,
    dmgBase: 50,
    dmgType: DamageType.etherial,
    energyRate: 128,
    fireRate: 16,
    baseAccuracy: .5,
    dmgRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .25),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .5),
  ),


  StockSystem.webSingularitron: WeaponData(
    systemData: ShipSystemData.fromStock(StockSystem.shdBasicEnergon,"Singularitron",
        mass: 10, baseCost: 200000, baseRepairCost: 5, powerDraw: 5),
    dmgDice: 8,
    dmgDiceSides: 1280,
    dmgBase: 250,
    dmgType: DamageType.gravitron,
    energyRate: 180,
    fireRate: 36,
    baseAccuracy: .5,
    dmgRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .25),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .5),
  ),
};
