import 'stock_pile.dart';
import '../systems/ship_system.dart';
import '../systems/weapons.dart';

final Map<StockSystem, WeaponData> stockWeapons = {
  StockSystem.fedLaser1: WeaponData(
    systemData: ShipSystemData("Fed Laser Mk 1",
        techLvl: StockSystem.fedLaser1.techLvl, rarity: StockSystem.fedLaser1.rarity,
        mass: 10, baseCost: 100, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 1,
    dmgDiceSides: 60,
    dmgBase: 1,
    dmgType: DamageType.photonic,
    energyRate: 20,
    fireRate: 10,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .5),
    accuracyRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .33),
  ),

  StockSystem.fedLaser2: WeaponData(
    systemData: ShipSystemData("Fed Laser Mk 2",
        techLvl: StockSystem.fedLaser2.techLvl, rarity: StockSystem.fedLaser2.rarity,
        mass: 10, baseCost: 250, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 4,
    dmgDiceSides: 20,
    dmgBase: 8,
    dmgType: DamageType.photonic,
    energyRate: 20,
    fireRate: 8,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .33),
    accuracyRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .25),
  ),

  StockSystem.fedLaser3: WeaponData(
    systemData: ShipSystemData("Fed Laser Mk 3",
        techLvl: StockSystem.fedLaser3.techLvl, rarity: StockSystem.fedLaser3.rarity,
        mass: 10, baseCost: 500, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 5,
    dmgDiceSides: 25,
    dmgBase: 12,
    dmgType: DamageType.photonic,
    energyRate: 20,
    fireRate: 8,
    baseAccuracy: .9,
    dmgRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .33),
    accuracyRangeConfig: const RangeConfig(idealRange: 1.5, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .2),
  ),

  StockSystem.plasmaRay: WeaponData(
    systemData: ShipSystemData("Plasma Ray",
        techLvl: StockSystem.plasmaRay.techLvl, rarity: StockSystem.plasmaRay.rarity,
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .5),
    dmgDice: 4,
    dmgDiceSides: 60,
    dmgBase: 16,
    dmgType: DamageType.plasma,
    energyRate: 36,
    fireRate: 16,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .2),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .1),
  ),

  StockSystem.gravRifle: WeaponData(
    systemData: ShipSystemData("Gravimetric Pulse Rifle",
        techLvl: StockSystem.gravRifle.techLvl, rarity: StockSystem.gravRifle.rarity,
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .6,
        slot: const SystemSlot(SystemSlotType.bauchmann,1)),
    dmgDice: 4,
    dmgDiceSides: 24,
    dmgBase: 16,
    dmgType: DamageType.gravitron,
    energyRate: 12,
    fireRate: 4,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .2),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 0, maxRange: 8, closeFalloff: .1, farFalloff: .1),
  ),

  StockSystem.vibraSlap: WeaponData(
    systemData: ShipSystemData("Cosmosonic Emitter",
        techLvl: StockSystem.vibraSlap.techLvl, rarity: StockSystem.vibraSlap.rarity,
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .6,
        slot: const SystemSlot(SystemSlotType.sinclair,1)),
    dmgDice: 8,
    dmgDiceSides: 24,
    dmgBase: 32,
    dmgType: DamageType.sonic,
    energyRate: 48,
    fireRate: 24,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 2, maxRange: 12, closeFalloff: .01, farFalloff: .05),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 2, maxRange: 12, closeFalloff: .01, farFalloff: .05),
  ),

  StockSystem.neuRad: WeaponData(
    systemData: ShipSystemData("Neutronic Radiator",
        techLvl: StockSystem.neuRad.techLvl, rarity: StockSystem.neuRad.rarity,
        mass: 10, baseCost: 1000, baseRepairCost: 1.5, powerDraw: .6,
        slot: const SystemSlot(SystemSlotType.sinclair,1)),
    dmgDice: 8,
    dmgDiceSides: 32,
    dmgBase: 24,
    dmgType: DamageType.neutrino,
    energyRate: 60,
    fireRate: 32,
    baseAccuracy: .8,
    dmgRangeConfig: const RangeConfig(idealRange: 2, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .1),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .1),
  ),

  StockSystem.thermalLance: WeaponData(
    systemData: ShipSystemData("Thermal Lance",
        techLvl: StockSystem.thermalLance.techLvl, rarity: StockSystem.thermalLance.rarity,
        mass: 10, baseCost: 2000, baseRepairCost: 1.5, powerDraw: .9,
        slot: const SystemSlot(SystemSlotType.sinclair,1)),
    dmgDice: 4,
    dmgDiceSides: 160,
    dmgBase: 50,
    dmgType: DamageType.fire,
    energyRate: 80,
    fireRate: 16,
    baseAccuracy: .5,
    dmgRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .25),
    accuracyRangeConfig: const RangeConfig(idealRange: 4, minRange: 1, maxRange: 8, closeFalloff: .1, farFalloff: .5),
  ),


};
